#!/usr/bin/zsh

# $1 is the first argument — the file or command to run

if [[ -z "$1" ]]; then
  echo "Usage: $0 <file-or-command-to-run>"
  exit 1
fi

# Default values
APP_ID="fzf-menu"
THEME="${THEME:-tokyonight}"
FONT="HackNerdFont-Regular:size=10"
SIZE="600x600"

if ! swaymsg -t get_tree | jq --arg app_id "$APP_ID" '.. | select(.app_id? == $app_id)' | grep -q "$APP_ID"; then
  exec foot \
    --app-id "$APP_ID" \
    --override "include=$HOME/dotfiles/foot/${THEME}.ini" \
    --font="$FONT" \
    --override="initial-window-size-pixels=${SIZE}" \
    -e "$1"

  # No window found, spawn it with the passed file/command
  ~/dotfiles/sway/run-foot -e "$1"
else
  # Window exists, focus it
  swaymsg "[class=\"fzf-menu\"] focus"
fi
