#!/usr/bin/zsh

# Emulator
resize-emulator() {
  change=$(echo "$1" | jq -r '.change')

  if [[ "$change" == "new" || "$change" == "close" ]]; then
    ~/dotfiles/sway/resize-emulator
  fi

}

# Listen to events
while true; do
  swaymsg -t subscribe '[ "window" ]' | while read -r line; do
    resize-emulator "$line"
  done
done

# If we get here, swaymsg exited
exit_code=${PIPESTATUS[0]} # get exit code of swaymsg
echo "swaymsg exited with code $exit_code. Exiting script."
exit $exit_code
