const a = (name) => (arg) => ({ _action: name, _arg: arg });

export const spawn = a('spawn');
export const quit = a('quit');
export const reload_config = a('reload_config');
export const focus_next = a('focus_next');
export const focus_prev = a('focus_prev');
export const focus_dir = a('focus_dir');
export const swap_dir = a('swap_dir');
export const resize_dir = a('resize_dir');
export const resize_tiled = a('resize_tiled');
export const focus_mon_left = a('focus_mon_left');
export const focus_mon_right = a('focus_mon_right');
export const send_mon_left = a('send_mon_left');
export const send_mon_right = a('send_mon_right');
export const view_tag = a('view_tag');
export const toggle_view_tag = a('toggle_view_tag');
export const tag = a('tag');
export const toggle_tag = a('toggle_tag');
export const toggle_floating = a('toggle_floating');
export const toggle_fullscreen = a('toggle_fullscreen');
export const set_layout = a('set_layout');
export const cycle_layout = a('cycle_layout');
export const move = a('move');
export const resize = a('resize');
export const kill_client = a('kill_client');
