[colors.primary]
background = '#1f2329'
foreground = '#a0a8b7'

[colors.cursor]
text = "#282c34"
cursor = "#dcdfe4"

[colors.normal]
black = "#1F1F1F"
red = "#e06c75"
green = "#98c379"
yellow = "#e5c07b"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#dcdfe4"

[colors.bright]
black = "#808080"
