#!/usr/bin/zsh

if [ -f ~/.env ]; then
  source ~/.env
fi

if [ "$ULTRAWIDE" ]; then
  FONT_SIZE=10
else
  FONT_SIZE=10.5
fi

kitty \
  -o font_size="$FONT_SIZE" \
  -o "include ~/dotfiles/kitty/${THEME:-nevermore}.conf" \
  "$@"
