#!/usr/bin/zsh

LOCAL="$1"
REMOTE="$2"

if [ -d "$LOCAL" ] && [ -d "$REMOTE" ]; then
  nvim "$LOCAL" "$REMOTE" +"CodeDiff dir $LOCAL $REMOTE"
else
  nvim "$LOCAL" "$REMOTE" +"CodeDiff file $LOCAL $REMOTE"
fi
