#!/usr/bin/zsh

source "$(dirname "$0")/scripts/library"

clear
echo "Installing wayland with sway wm..."
echo "----------------------------------"
echo ""

packages=(
  "grim"
  "grimshot"
  "polkit"
  "rofi-power-menu"
  "rofi-wayland"
  "sway"
  "swaybg"
  "swaydim"
  "swayidle"
  "waybar"
  "wl-clipboard"
  "xdg-desktop-portal-wlr"
  "xorg-xwayland"
)

install_packages "${packages[@]}"

print_success "DONE!"
