require("config.options")
require("config.filetype")
require("config.autocmd")
require("config.keymap")
require("config.lazy")
require("config.lsp")
require("config.diagnostic")
require("config.netrw")
