"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[manager.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "p"
run = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[manager.prepend_keymap]]
on = ["g", "r"]
run = '''
	shell 'ya emit cd "$(git rev-parse --show-toplevel)"'
'''
[[manager.prepend_keymap]]
on = ["R"]
run = '''
    shell 'ripdrag "$@" -x 2>/dev/null &' --confirm
'''
