#!/usr/bin/zsh

source ~/.env

if [ "$ULTRAWIDE" ] || [ "$XDG_SESSION_TYPE" = "wayland" ]; then
  rofi -config ~/dotfiles/rofi/"${THEME:-tokyonight}".rasi "$@"
else
  rofi -config ~/dotfiles/rofi/"${THEME:-tokyonight}".rasi "$@" -dpi 152
fi
