#!/usr/bin/zsh

source ~/.env

rofi_cmd=(
  rofi
  -config "$HOME/dotfiles/rofi/${THEME:-nevermore}.rasi"
)

if [ "$ULTRAWIDE" ] || [ "$XDG_SESSION_TYPE" = "wayland" ]; then
  "${rofi_cmd[@]}" "$@"
else
  "${rofi_cmd[@]}" -dpi 152 "$@"
fi
