#!/usr/bin/zsh

[[ "$XDG_SESSION_TYPE" == "wayland" ]] || exit 0

if [ -f ~/.env ]; then
  source ~/.env
fi

killall waybar

STYLE="$HOME/dotfiles/waybar/themes/${THEME:-linux_tty}.css"

waybar --style "$STYLE"
