#!/usr/bin/zsh

set -eu

# Color palette
tokyonight="#7aa2f7"
nevermore="#7aa2f7"
vscode="#569CD6"

CONFIG_FILE="$HOME/dotfiles/waybar/config.jsonc"
THEME="${1:-nevermore}"

case "$THEME" in
tokyonight)
  NEW_COLOR="$tokyonight"
  ;;
nevermore)
  NEW_COLOR="$nevermore"
  ;;
vscode)
  NEW_COLOR="$vscode"
  ;;
*)
  echo "Error: unknown theme '$THEME'"
  exit 1
  ;;
esac

sed -i \
  "s/<span[[:space:]]\\+color=['\"][^'\"]*['\"]/<span color='${NEW_COLOR}'/g" \
  "$CONFIG_FILE"

echo "Waybar span color set to $THEME ($NEW_COLOR)"
