#!/usr/bin/zsh

source "$HOME/dotfiles/scripts/library"

clear
echo "Installing wayland with sway wm..."
echo "----------------------------------"
echo ""

packages=(
  "foot"
  "foot-terminfo"
  "polkit"
  "sway"
  "swaybg"
  "swaydim"
  "swayidle"
  "waybar"
  "wl-clipboard"
  "xdg-desktop-portal-wlr"
  "xorg-xwayland"
)

install_packages "${packages[@]}"

print_success "DONE!"
