#!/usr/bin/zsh

source "$HOME/dotfiles/scripts/library"

clear
echo "Installing xorg with i3wm..."
echo "----------------------------"
echo ""

packages=(
  "i3-wm"
  "picom"
  "polybar"
  "xidlehook"
  "xorg"
  "xorg-xinit"
  "xorg-xinput"
  "xsel"
  "xwallpaper"
)

install_packages "${packages[@]}"

~/dotfiles/st/build

print_success "DONE!"
