#!/usr/bin/zsh

source "$HOME/dotfiles/scripts/library"

clear
echo "Applying application configs..."
echo "-------------------------------"
echo ""

if [ -d ~/.config ]; then
  print_info ".config folder already exists."
else
  mkdir ~/.config
  print_success ".config folder created."
fi

# Create symbolic links

# create dirs
mkdir -p "$HOME/.ssh"
mkdir -p "$HOME/.local/share/applications"
mkdir -p "$HOME/.config/BraveSoftware/Brave-Browser/Default/Web Applications/Manifest Resources/"
sudo mkdir -p "/usr/share/chromium/extensions"

# linking
sudo ln -sf "$HOME/dotfiles/environment" /etc/environment
sudo ln -sf "$HOME/dotfiles/systemd/coredump.conf.d" /etc/systemd/coredump.conf.d
sudo ln -sf "$HOME/dotfiles/systemd/system/performance.service" /etc/systemd/system/performance.service
sudo ln -sf "$HOME/dotfiles/systemd/user/goimapnotify.service" /etc/systemd/user/goimapnotify.service
sudo ln -sf "$HOME/dotfiles/systemd/user/mbsync.service" /etc/systemd/user/mbsync.service
sudo ln -sf "$HOME/dotfiles/xorg/xorg.conf" "/etc/X11/xorg.conf"

create_symlink "$HOME/dotfiles/bin" "$HOME/.local/bin"
create_symlink "$HOME/dotfiles/shell/zsh/.zshenv" "$HOME/.zshenv"
create_symlink "$HOME/dotfiles/shell/zsh/.zprofile" "$HOME/.zprofile"
create_symlink "$HOME/dotfiles/shell/zsh/.zshrc" "$HOME/.zshrc"
create_symlink "$HOME/dotfiles/shell/bash/.bashrc" "$HOME/.bashrc"
create_symlink "$HOME/dotfiles/shell/bash/.bash_profile" "$HOME/.bash_profile"
create_symlink "$HOME/dotfiles/alacritty" "$HOME/.config/alacritty"
create_symlink "$HOME/dotfiles/kitty" "$HOME/.config/kitty"
create_symlink "$HOME/dotfiles/nvim" "$HOME/.config/nvim"
create_symlink "$HOME/dotfiles/vim" "$HOME/.config/vim"
create_symlink "$HOME/dotfiles/dunst" "$HOME/.config/dunst"
create_symlink "$HOME/dotfiles/ssh/config" "$HOME/.ssh/config"
create_symlink "$HOME/dotfiles/xorg/.xinitrc" "$HOME/.xinitrc"
create_symlink "$HOME/dotfiles/xorg/.xscreensaver" "$HOME/.xscreensaver"
create_symlink "$HOME/dotfiles/xorg/.Xresources" "$HOME/.Xresources"
create_symlink "$HOME/dotfiles/i3" "$HOME/.config/i3"
create_symlink "$HOME/dotfiles/picom" "$HOME/.config/picom"
create_symlink "$HOME/dotfiles/git" "$HOME/.config/git"
create_symlink "$HOME/dotfiles/.ideavimrc" "$HOME/.ideavimrc"
create_symlink "$HOME/dotfiles/tmux/.tmux.conf" "$HOME/.tmux.conf"
create_symlink "$HOME/dotfiles/.tool-versions" "$HOME/.tool-versions"
create_symlink "$HOME/dotfiles/pipewire" "$HOME/.config/pipewire"
create_symlink "$HOME/dotfiles/polybar" "$HOME/.config/polybar"
create_symlink "$HOME/dotfiles/emacs" "$HOME/.config/emacs"
create_symlink "$HOME/dotfiles/yazi" "$HOME/.config/yazi"
create_symlink "$HOME/dotfiles/sway" "$HOME/.config/sway"
create_symlink "$HOME/dotfiles/waybar" "$HOME/.config/waybar"
create_symlink "$HOME/dotfiles/foot" "$HOME/.config/foot"
create_symlink "$HOME/dotfiles/flameshot" "$HOME/.config/flameshot"
create_symlink "$HOME/dotfiles/lazygit" "$HOME/.config/lazygit"
create_symlink "$HOME/dotfiles/bat" "$HOME/.config/bat"
create_symlink "$HOME/dotfiles/fontconfig" "$HOME/.config/fontconfig"
create_symlink "$HOME/dotfiles/paru" "$HOME/.config/paru"
create_symlink "$HOME/dotfiles/brave/brave-flags.conf" "$HOME/.config/brave-flags.conf"
create_symlink "$HOME/dotfiles/qt6ct" "$HOME/.config/qt6ct"
create_symlink "$HOME/dotfiles/eza" "$HOME/.config/eza"
create_symlink "$HOME/dotfiles/gnupg" "$HOME/.config/gnupg"
create_symlink "$HOME/dotfiles/isync/.mbsyncrc" "$HOME/.mbsynrc"
create_symlink "$HOME/dotfiles/oama" "$HOME/.config/oama"
create_symlink "$HOME/dotfiles/goimapnotify" "$HOME/.config/goimapnotify"
create_symlink "$HOME/dotfiles/neomutt" "$HOME/.config/neomutt"

./eza/apply-eza-theme

sudo ln -sf "$HOME/dotfiles/brave/extensions/fmkadmapgofadopljbjfkapdkoienihi.json" "/usr/share/chromium/extensions/fmkadmapgofadopljbjfkapdkoienihi.json"
sudo ln -sf "$HOME/dotfiles/brave/extensions/eimadpbcbfnmbkopoojfekhnkhdbieeh.json" "/usr/share/chromium/extensions/eimadpbcbfnmbkopoojfekhnkhdbieeh.json"
sudo ln -sf "$HOME/dotfiles/brave/extensions/nngceckbapebfimnlniiiahkandclblb.json" "/usr/share/chromium/extensions/nngceckbapebfimnlniiiahkandclblb.json"

sudo chmod 644 /usr/share/chromium/extensions/fmkadmapgofadopljbjfkapdkoienihi.json
sudo chmod 644 /usr/share/chromium/extensions/eimadpbcbfnmbkopoojfekhnkhdbieeh.json
sudo chmod 644 /usr/share/chromium/extensions/nngceckbapebfimnlniiiahkandclblb.json

# Librewolf
LIBREWOLF_CONFIG="$HOME/.librewolf/librewolf.overrides.cfg"

if [ ! -f "$LIBREWOLF_CONFIG" ]; then
  mkdir -p "$(dirname "$LIBREWOLF_CONFIG")"
  touch "$LIBREWOLF_CONFIG"
fi

create_symlink "$HOME/dotfiles/librewolf/librewolf.overrides.cfg" "$LIBREWOLF_CONFIG"

sudo -E python3 ~/dotfiles/librewolf/merge-policies.py

print_success "DONE!"
