#!/usr/bin/zsh

source "$HOME/dotfiles/scripts/library"

clear
echo "Applying system config..."
echo "-------------------------"

sudo usermod -aG wheel,audio,video,docker,network,adm,input,storage "$USER"

print_info "Enabling systemctl daemons..."
loginctl enable-linger
sudo systemctl enable --now iwd
sudo systemctl enable --now bluetooth
sudo systemctl enable --now sshd
sudo systemctl enable --now avahi-daemon
sudo systemctl enable --now power-profiles-daemon
systemctl enable --user --now goimapnotify
systemctl enable --user --now mbsync.timer

print_info "Setting up gnome settings..."
if command -v gsettings &>/dev/null; then
  gsettings set org.gnome.desktop.interface gtk-theme Default-dark
  gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
  gsettings set org.gnome.desktop.interface icon-theme Adwaita
  gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 33
  gsettings set org.gnome.desktop.peripherals.keyboard delay 220
  gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('xkb', 'gr')]"
  gsettings set org.gnome.desktop.wm.keybindings switch-windows "['<Alt>Tab']"
fi

print_info "Setting up tmux..."
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
~/.tmux/plugins/tpm/bin/install_plugins
tmux source ~/.tmux.conf

print_info "Setting up asdf..."
# Generate asdf completions
COMPLETIONS_DIR="${ASDF_DATA_DIR:-$HOME/.asdf}/completions"
PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

if [ ! -d "$COMPLETIONS_DIR" ]; then
  mkdir -p "$COMPLETIONS_DIR"
  asdf completion zsh >"$COMPLETIONS_DIR/_asdf"
fi

## Add asdf plugins
asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf plugin add java https://github.com/halcyon/asdf-java.git

# Read .tool-versions file and install the specified versions
cd ~
asdf install

print_info "Configuring java... (for the current session only)"
. ~/.asdf/plugins/java/set-java-home.zsh

print_info "Increasing file descriptor and inotify limits..."
# Check current limit
ulimit -Sn
# Change limit (temporary)
ulimit -Sn 10000 # You might need to change the hard limit too

# Change limits (temporary)
sudo sysctl fs.inotify.max_queued_events=16384
sudo sysctl fs.inotify.max_user_instances=8192
sudo sysctl fs.inotify.max_user_watches=524288

grep -qxF '* - nofile 65536' /etc/security/limits.conf || echo '* - nofile 65536' | sudo tee -a /etc/security/limits.conf
grep -qxF 'DefaultLimitNOFILE=65536' /etc/systemd/system.conf || echo 'DefaultLimitNOFILE=65536' | sudo tee -a /etc/systemd/system.conf
grep -qxF 'DefaultLimitNOFILE=65536' /etc/systemd/user.conf || echo 'DefaultLimitNOFILE=65536' | sudo tee -a /etc/systemd/user.conf

print_info "Setting up docker..."
ls -al /dev/kvm
sudo usermod -aG kvm $USER
sudo usermod -aG docker $USER
docker --version
# .socket instead of .service to start docker deamon only when needed
sudo systemctl enable --now docker.socket
docker context use default
docker compose version

print_info "Configuring NodeJS..."
corepack enable pnpm
corepack enable yarn
asdf reshim nodejs

print_info "Installing global npm packages..."
npm i -g npm-workspaces-language-server corepack@latest

print_info "Setting xdg default web browser..."
ORIGINAL_BROWSER=$BROWSER
unset BROWSER
xdg-settings set default-web-browser brave-browser.desktop
export BROWSER=$ORIGINAL_BROWSER

print_info "Installing yazi plugins..."
ya pkg add yazi-rs/plugins:git
ya pkg add yazi-rs/plugins:smart-enter
ya pkg add yazi-rs/plugins:smart-paste
ya pkg add aresler/path-from-root
ya pkg add llanosrocas/githead

print_info "Downloading tldr cache..."
tldr --update

print_info "Generating zsh completions..."
~/dotfiles/scripts/setup-completions

print_info "Install GTK Tokyonight theme..."
~/dotfiles/scripts/install-tokyonight-gtk

print_info "Installing tmp plugins..."
~/.tmux/plugins/tpm/bin/clean_plugins all

print_info "Removing thunar extra desktop files..."
sudo rm -rf /usr/share/applications/{thunar-bulk-rename.desktop,thunar-settings.desktop}

print_info "Setting up git remote..."
# Check if the remote origin URL is set and if it's using SSH or HTTP
remote_url=$(git remote get-url origin 2>/dev/null)

if [[ -z "$remote_url" ]]; then
  echo "No remote 'origin' configured. Adding SSH origin..."
  git remote add origin git@github.com:AkisArou/dotfiles.git
else
  if [[ "$remote_url" != git@github.com:* ]]; then
    echo "Remote origin is not configured via SSH."
    echo "Removing HTTP origin..."
    git remote remove origin

    echo "Adding SSH origin..."
    git remote add origin git@github.com:AkisArou/dotfiles.git

    echo "Setting upstream branch of main to origin/main..."
    git branch --set-upstream-to=origin/main main
  else
    echo "Remote origin is already configured via SSH."
  fi
fi

print_success "DONE!"
