#!/bin/bash

source "$(dirname "$0")/scripts/library"

sudo usermod -aG wheel akisarou

sudo cp "/home/akisarou/dotfiles/sudoers.d/sudoers" /etc/sudoers.d/sudoers
sudo chown root:root /etc/sudoers.d/sudoers

sudo cp -f "home/akisarou/dotfiles/systemd/network" /etc/systemd/network
sudo chown root:root /etc/systemd/network

sudo apt install zsh

# Check if the current shell is zsh
if [[ "$SHELL" != */zsh ]]; then
  print_info "Current shell is not zsh. Changing default shell to zsh..."
  chsh -s $(which zsh)
else
  print_success "Current shell is already zsh."
fi

print_success "DONE!"
