#!/usr/bin/zsh

source "$(dirname "$0")/scripts/library"

clear
echo "Installing xorg with i3wm..."
echo "----------------------------"
echo ""

packages=(
  "i3-wm"
  "nitrogen"
  "picom"
  "polybar"
  #"xidlehook"
  "xorg"
  "xorg-dev"
  "xinit"
  "xinput"
  "xsel"
)

install_packages "${packages[@]}"

~/dotfiles/st/build

print_success "DONE!"
