icons_format = "{icon}"

[theme]
theme = "native"

[icons]
icons = "awesome4"

[[block]]
block = "packages"
package_manager = ["pacman", "aur"]
interval = 600
error_interval = 300
format = " $icon $total updates available "
format_singular = " $icon $total update available "
format_up_to_date = " $icon system OK "
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
aur_command = "yay -Qua"
[[block.click]]
button = "left"
cmd = "alacritty -e zsh -c 'yay'"

[[block]]
block = "cpu"
format = " CPU $utilization "
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " MEM $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
format = " VOL {$volume.eng(w:2) |}"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "battery"
format = " $percentage"
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[[block]]
block = "bluetooth"
mac = "14:88:E6:8C:08:A8"
disconnected_format = ""
format = " $icon $name"
