#!/usr/bin/zsh

THEME="${1:-vscode}"

case "$THEME" in
vscode | VSCode-Dark)
  GTK_THEME_NAME="VSCode-Dark"
  ;;
*)
  echo "GTK theme not found: $THEME"
  exit 1
  ;;
esac

THEME_DIR="$HOME/dotfiles/gtk/themes/$GTK_THEME_NAME"

[ -d "$THEME_DIR" ] || {
  echo "GTK theme directory not found: $THEME_DIR"
  exit 1
}

mkdir -p "$HOME/.themes" "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0"
ln -sfn "$THEME_DIR" "$HOME/.themes/$GTK_THEME_NAME"

cat >"$HOME/.config/gtk-3.0/settings.ini" <<EOF
[Settings]
gtk-theme-name=$GTK_THEME_NAME
gtk-application-prefer-dark-theme=true
gtk-icon-theme-name=Adwaita
gtk-cursor-theme-name=Adwaita
EOF

cat >"$HOME/.config/gtk-4.0/settings.ini" <<EOF
[Settings]
gtk-theme-name=$GTK_THEME_NAME
gtk-application-prefer-dark-theme=true
gtk-icon-theme-name=Adwaita
gtk-cursor-theme-name=Adwaita
EOF

cat >"$HOME/.gtkrc-2.0" <<EOF
gtk-theme-name="$GTK_THEME_NAME"
gtk-icon-theme-name="Adwaita"
gtk-cursor-theme-name="Adwaita"
EOF

if command -v gsettings >/dev/null 2>&1; then
  gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME_NAME"
  gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
fi

echo "GTK theme set to $GTK_THEME_NAME"
