#!/usr/bin/zsh

if [ "$ULTRAWIDE" ]; then
  ~/dotfiles/st/st -s 0.9 -f "HackNerdFont-Regular:pixelsize=14:antialias=true:autohint=true"
else
  ~/dotfiles/st/st -s 0.9 -f "HackNerdFont-Regular:pixelsize=25:antialias=true:autohint=true"
fi
