#!/usr/bin/bash

HISTFILE="$HOME/.bash_history"
HISTCONTROL=ignoredups:erasedups
HISTSIZE=1000000
HISTFILESIZE=1000000
export -n HISTFILE HISTCONTROL HISTSIZE HISTFILESIZE

shopt -s histappend cmdhist
