[package]
name = "sense-zsh-module"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
native-module = ["sense-zsh-sys/native-bindings"]

[dependencies]
sense-zsh-sys = { path = "../sense-zsh-sys" }

[lints.rust]
unsafe_code = "allow"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
must_use_candidate = "allow"
