#!/usr/bin/zsh

# Kill already running dublicate process
_ps="waybar swaybg"
for _prs in $_ps; do
    if [ "$(pidof "${_prs}")" ]; then
         killall -9 "${_prs}"
    fi
done

swaybg --output '*' --mode fill  --image /home/akisarou/dotfiles/wallpapers/tokyo-lofi-street-2.jpg &
. /home/akisarou/dotfiles/waybar/launch-waybar &
exec dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=wlroots
