#!/usr/bin/zsh

# completions
autoload -Uz compinit 
if [[ -n ${ZDOTDIR}/.zcompdump(#qN.mh+24) ]]; then
	compinit;
else
	compinit -C;
fi;

fpath=(${ASDF_DATA_DIR:-$HOME/.asdf}/completions $fpath)
source "$HOME/dotfiles/scripts/try-source-completions"
