#!/usr/bin/zsh

autoload -Uz zrecompile
autoload -Uz compinit
dump=$ZSH_COMPDUMP

if [[ -s $dump(#qN.mh+24) && (! -s "$dump.zwc" || "$dump" -nt "$dump.zwc") ]]; then
    compinit -i d $ZSH_COMPDUMP
    zrecompile $ZSH_COMPDUMP
fi

compinit -C
