#!/usr/bin/zsh

typeset -g HISTFILE="$HOME/.zsh_history"
typeset -gi HISTSIZE=1200000
typeset -gi SAVEHIST=1000000
typeset +x HISTFILE HISTSIZE SAVEHIST

## History command configuration
setopt BANG_HIST              # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY       # Write the history file in the ":start:elapsed;command" format.
setopt SHARE_HISTORY          # Share history between all sessions.
setopt HIST_FCNTL_LOCK        # Coordinate concurrent writers with operating-system locks.
setopt HIST_EXPIRE_DUPS_FIRST # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_ALL_DUPS   # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS      # Do not display a line previously found.
setopt HIST_IGNORE_SPACE      # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS      # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS     # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY            # Don't execute immediately upon history expansion.
