#!/usr/bin/zsh

WORDCHARS=${WORDCHARS//\//}

zstyle ':completion:*' menu yes select
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'

zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup

zmodload zsh/complist

_comp_options+=(globdots) # Include hidden files.

unsetopt BEEP
setopt AUTO_CD
setopt GLOB_DOTS
setopt NOMATCH
setopt MENU_COMPLETE
setopt EXTENDED_GLOB
setopt INTERACTIVE_COMMENTS
setopt APPEND_HISTORY

ZSH_AUTOSUGGEST_ENABLED=0

function autosuggest-toggle() {
  if ! typeset -f _zsh_autosuggest_start >/dev/null; then
    zinit load zsh-users/zsh-autosuggestions
  fi

  if [[ $ZSH_AUTOSUGGEST_ENABLED -eq 1 ]]; then
    _zsh_autosuggest_disable
    ZSH_AUTOSUGGEST_ENABLED=0
  else
    _zsh_autosuggest_enable
    ZSH_AUTOSUGGEST_ENABLED=1
  fi
}

# autosuggestions
zle -N autosuggest-toggle
bindkey '^E' autosuggest-accept
bindkey '^G' autosuggest-toggle

bindkey -M menuselect '^N' down-line-or-history
bindkey -M menuselect '^P' up-line-or-history

# Open nvim with Alt+e like fish
bindkey -s '\ee' 'v\n'
