#!/usr/bin/zsh

bindkey -v # enable vi mode

zle_highlight=(region:bg="#292e42" paste:none)

###########
# Options #
###########

# Make word movement consistent with vim
autoload -Uz select-word-style
select-word-style bash


##########
# Cursor #
##########

# Change cursor shape for different vi modes.
autoload -Uz add-zle-hook-widget

_dotfiles_cursor_keymap_select() {
  case $KEYMAP in
    vicmd) printf '\e[1 q' ;;      # block
    viins|main) printf '\e[5 q' ;; # beam
  esac
}

_dotfiles_cursor_line_init() {
  zle -K viins
  printf '\e[5 q'
}

_dotfiles_cursor_line_finish() {
  printf '\e[5 q'
}

add-zle-hook-widget keymap-select _dotfiles_cursor_keymap_select
add-zle-hook-widget line-init _dotfiles_cursor_line_init
add-zle-hook-widget line-finish _dotfiles_cursor_line_finish


############
# Keydings #
############
bindkey -M viins '^R' fzf-history-widget # fzf should be sourced first
vi-redo() { zle redo }
zle -N vi-redo
bindkey -M vicmd '^R' vi-redo

# allow vv to edit the command line (standard behaviour)
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd 'vv' edit-command-line


bindkey -M viins '^H' backward-delete-char # ^H is same as ^h
bindkey -M viins '^W' backward-kill-word

############
# Surround #
############

autoload -Uz surround

zle -N delete-surround surround
zle -N add-surround surround
zle -N change-surround surround

bindkey -M vicmd sr change-surround
bindkey -M vicmd sd delete-surround
bindkey -M vicmd sa add-surround
bindkey -M visual sa add-surround

autoload -U select-bracketed
zle -N select-bracketed
for m in visual viopp; do
  for c in {a,i}${(s..)^:-'()[]{}<>bB'}; do
    bindkey -M $m $c select-bracketed
  done
done

autoload -U select-quoted
zle -N select-quoted
for m in visual viopp; do
  for c in {a,i}{\',\",\`}; do
    bindkey -M $m $c select-quoted
  done
done

# Function to select any quote (single, double, or backtick)
select-any-quote() {
  emulate -L zsh

  local -a quote_types=("'" '"' '`')
  local quote best_quote
  local -i index opening backslash_count check_pos
  local -i cursor_position=$((CURSOR + 1))
  local -i distance span best_distance=-1 best_span=-1

  for quote in $quote_types; do
    opening=0

    for (( index = 1; index <= ${#BUFFER}; index++ )); do
      [[ $BUFFER[index] == $quote ]] || continue

      backslash_count=0
      check_pos=$((index - 1))
      while (( check_pos >= 1 )) && [[ $BUFFER[check_pos] == \\ ]]; do
        ((backslash_count++))
        ((check_pos--))
      done
      (( backslash_count % 2 )) && continue

      if (( ! opening )); then
        opening=$index
        continue
      fi

      span=$((index - opening))
      if (( cursor_position < opening )); then
        distance=$((opening - cursor_position))
      elif (( cursor_position > index )); then
        distance=$((cursor_position - index))
      else
        distance=0
      fi

      if (( best_distance < 0 || distance < best_distance ||
            (distance == best_distance && span < best_span) )); then
        best_quote=$quote
        best_distance=$distance
        best_span=$span
      fi

      opening=0
    done
  done

  [[ -n $best_quote ]] || return 1
  zle select-quoted "${KEYS[1]}${best_quote}"
}

# Register the widget
zle -N select-any-quote

# Bind to q for "quote" in both visual and operator modes
for m in visual viopp; do
  for c in {a,i}q; do
    bindkey -M $m $c select-any-quote
  done
done
