#!/usr/bin/zsh

# init
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

zinit ice src"pure.zsh"
zinit light sindresorhus/pure

zinit light romkatv/zsh-defer
source "$HOME/.local/share/zinit/plugins/romkatv---zsh-defer/zsh-defer.plugin.zsh"

zsh-defer zinit light zsh-users/zsh-autosuggestions

zsh-defer zinit light zdharma-continuum/fast-syntax-highlighting

zsh-defer zinit light Aloxaf/fzf-tab

zsh-defer zinit light kutsan/zsh-system-clipboard
