#!/usr/bin/zsh

# init
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# plugins
zinit light zsh-users/zsh-autosuggestions

zinit light zdharma-continuum/fast-syntax-highlighting

function zvm_config() {
  ZVM_INIT_MODE=sourcing
  ZVM_VI_SURROUND_BINDKEY=s-prefix
  ZVM_VI_INSERT_ESCAPE_BINDKEY=jk
  WORDCHARS=${WORDCHARS//\/}
}
zinit ice depth=1
zinit light jeffreytse/zsh-vi-mode

zinit light Aloxaf/fzf-tab
