#!/usr/bin/zsh

THEME="${1:-nevermore}"

SELECTED_THEME_FILE="$HOME/dotfiles/xorg/.Xresources.d/$THEME"
THEME_FILE="$HOME/dotfiles/xorg/.Xresources.d/theme"

[ -f "$SELECTED_THEME_FILE" ] || {
  echo "Xresources theme not found: $THEME"
  exit 1
}

ln -sf "$SELECTED_THEME_FILE" "$THEME_FILE"
