[package]
name = "shell-sense"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
etcetera.workspace = true
futures-util.workspace = true
nix.workspace = true
sense-config = { path = "../sense-config" }
sense-blink = { path = "../sense-blink" }
sense-daemon = { path = "../sense-daemon" }
sense-model = { path = "../sense-model" }
sense-present = { path = "../sense-present" }
sense-protocol = { path = "../sense-protocol" }
sense-shell-worker = { path = "../sense-shell-worker" }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
unicode-width.workspace = true

[lints]
workspace = true
