#!/bin/sh

INSTALL_DIR="$HOME/bitlbee"
REPO_URL="https://github.com/bitlbee/bitlbee"
NAME="Bitlbee"

build_bitlbee() {
  ./configure --prefix=/usr --purple=1 --ssl=gnutls
  make
  sudo make install
  sudo make install-systemd
  sudo make install-dev
}

BUILD_CALLBACK="build_bitlbee"

. "$HOME"/dotfiles/scripts/build-from-source
