#!/bin/sh

INSTALL_DIR="$HOME/emacs"
REPO_URL="https://git.savannah.gnu.org/git/emacs.git"
NAME="Emacs"

build_emacs() {
  ./autogen.sh

  ./configure --sysconfdir=/etc --prefix=/usr --libexecdir=/usr/lib --localstatedir=/var \
    --disable-build-details --with-cairo --with-harfbuzz --with-libsystemd --with-modules \
    --with-native-compilation=aot --with-tree-sitter --without-x --without-sound

  CC=clang make -j8
  sudo make install
}

BUILD_CALLBACK="build_emacs"

. "$HOME"/dotfiles/scripts/build-from-source
