#!/usr/bin/zsh

VALID_THEMES=("vscode" "tokyonight" "linux_tty")

SELECTED_THEME=$1

if [[ ! " ${VALID_THEMES[@]} " =~ " ${SELECTED_THEME} " ]]; then
  echo "Invalid theme! \nOptions: ${VALID_THEMES[*]}"
  exit 1
fi

~/dotfiles/scripts/create-template-env

# Use sed for in-place editing to replace or add THEME=$SELECTED_THEME
sed -i "s/^THEME=.*/THEME=$SELECTED_THEME/" "$HOME/.env" 2>/dev/null

# If THEME was not replaced, add it
if ! grep -q "^THEME=" "$HOME/.env"; then
  echo "THEME=$SELECTED_THEME" >>"$HOME/.env"
fi

echo "THEME set to $SELECTED_THEME in ~/.env"

# waybar
killall waybar
~/dotfiles/waybar/launch-waybar &

if [ -f "~/dotfiles/eza/${SELECTED_THEME}.yml" ]; then
  ln -sf "~/dotfiles/eza/${SELECTED_THEME}.yml" ~/.config/eza/theme.yml
else
  ln -sf "~/dotfiles/eza/tokyonight.yml" ~/.config/eza/theme.yml
fi

# tmux
tmux source ~/dotfiles/tmux/.tmux.conf
tmux source ~/dotfiles/tmux/"$SELECTED_THEME".tmux

# p10k
p10k reload

export THEME=$SELECTED_THEME
source ~/.zshrc
