#!/usr/bin/zsh

VALID_THEMES=("tokyonight" "linux_tty")

SELECTED_THEME=$1

if [[ ! " ${VALID_THEMES[@]} " =~ " ${SELECTED_THEME} " ]]; then
  echo "Invalid theme! \nOptions: ${VALID_THEMES[*]}"
  exit 1
fi

~/dotfiles/scripts/create-template-env

# Use sed for in-place editing to replace or add THEME=$SELECTED_THEME
sed -i "s/^THEME=.*/THEME=$SELECTED_THEME/" "$HOME/.env" 2>/dev/null

# If THEME was not replaced, add it
if ! grep -q "^THEME=" "$HOME/.env"; then
  echo "THEME=$SELECTED_THEME" >>"$HOME/.env"
fi

echo "THEME set to $SELECTED_THEME in ~/.env"

# waybar
"$HOME/dotfiles/waybar/set-theme" $THEME
killall waybar
~/dotfiles/waybar/launch-waybar &

# eza
"$HOME/dotfiles/eza/set-theme" $THEME

# tmux
tmux source ~/dotfiles/tmux/.tmux.conf
tmux source ~/dotfiles/tmux/"$SELECTED_THEME".tmux

# p10k
p10k reload

# xResources
"$HOME/dotfiles/xorg/set-theme" $THEME

# Polybar
"$HOME/dotfiles/polybar/set-theme" $THEME
"$HOME/dotfiles/polybar/init"

export THEME=$SELECTED_THEME
source ~/.zshrc
