#!/usr/bin/zsh

if [ ! -f "$HOME/.env" ]; then
  touch "$HOME/.env"
  echo 'DESKTOP_MAC=""' >>"$HOME/.env"
  echo "THEME=tokyonight" >>"$HOME/.env"
  echo "EXPO_TOKEN=12345" >>"$HOME/.env"
  echo "Created ~/.env file."
fi
