#!/usr/bin/zsh

cpu_is_intel() {
  grep -qm1 '^vendor_id[[:space:]]*:.*GenuineIntel' /proc/cpuinfo
}

gpu_has_amd() {
  lspci | grep -Eqi '(vga|3d|display).*amd'
}

gpu_has_intel() {
  lspci | grep -Eqi '(vga|3d|display).*intel'
}
