#!/usr/bin/zsh

source "$(dirname "$0")/library"

print_info "Checking orphan packages..."
orphans=$(paru -Qdtq)

if [[ -z "$orphans" ]]; then
  echo "No orphan packages found."
else
  echo "The following orphan packages were found:"
  echo "$orphans"

  # Ask user if they want to remove them
  read "response?Do you want to remove these packages? (y/N) "

  if [[ "$response" =~ ^[Yy]$ ]]; then
    paru -Rns $orphans
  else
    echo "Skipping package removal."
  fi
fi

echo
print_info "Clearing ~/.cache"
home_cache_used="$(du -sh ~/.cache)"
rm -rf ~/.cache/
echo "Spaced saved: $home_cache_used"

echo
print_info "Clearing system logs"
journalctl --vacuum-time=7d
