#!/usr/bin/zsh

source "$(dirname "$0")/library"

print_info "Checking orphan packages..."
orphans=$(paru -Qdtq)

if [[ -z "$orphans" ]]; then
  echo "No orphan packages found."
else
  echo "The following orphan packages were found:"
  paru -Qdtq | paru -Rns -
fi

echo
print_info "Clearing ~/.cache"
home_cache_used="$(du -sh ~/.cache)"
rm -rf ~/.cache/
echo "Spaced saved: $home_cache_used"

echo
print_info "Clearing system logs"
sudo journalctl --vacuum-time=7d

echo
print_info "Building bat cache..."
bat cache --build
