#!/usr/bin/zsh

source ~/dotfiles/shell/common/exports

tmux has-session -t default 2>/dev/null ||
  tmux new-session -s default -d

tmux has-session -t work 2>/dev/null ||
  tmux new-session -s work -d -c ~/nable-solutions
