#!/usr/bin/zsh

FONT_FAMILY="Hack Nerd Font Mono"

if [ "$ULTRAWIDE" ]; then
  POLY_FONT="$FONT_FAMILY":size=9
  POLY_BAR_HEIGHT="16pt"
else
  POLY_FONT="$FONT_FAMILY":size=20
  POLY_BAR_HEIGHT="30pt"
fi

export POLY_FONT
export POLY_BAR_HEIGHT

killall polybar
polybar default &
