#!/usr/bin/zsh

FONT_FAMILY="Hasklug Nerd Font Mono"

if [[ $ULTRAWIDE == 1 ]]; then
  POLY_FONT="$FONT_FAMILY":size=9
  POLY_BAR_HEIGHT="16pt"
else
  POLY_FONT="$FONT_FAMILY":size=14\;3
  POLY_BAR_HEIGHT="20pt"
fi

export POLY_FONT
export POLY_BAR_HEIGHT

killall polybar
polybar default &
