#!/usr/bin/zsh

[[ "$XDG_SESSION_TYPE" == "x11" ]] || exit 0

FONT_FAMILY="Hack Nerd Font Mono"

if [ "$ULTRAWIDE" ]; then
  POLY_FONT="$FONT_FAMILY":size=9
  POLY_BAR_HEIGHT="16pt"
else
  POLY_FONT="$FONT_FAMILY":size=15
  POLY_BAR_HEIGHT="22pt"
fi

export POLY_FONT
export POLY_BAR_HEIGHT

killall polybar
polybar default &
