#!/usr/bin/zsh

alias sudo="sudo -E"
alias vim="TERM=xterm-256color vim"
alias v="nvim"
alias e="nvim ."
alias info="info --vi-keys"
alias dir="dir --color=auto"
alias grep="grep --color=auto"
alias ip="ip -color=auto"

alias lg="lazygit"
alias c="nvim -c 'terminal codex resume --last'"

alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

alias df="df -h"
alias free="free -m"

alias cat="bat"

eza_base="eza --group-directories-first --icons=never"
alias ls="$eza_base"
alias ll="$eza_base -lh --git"
alias la="$eza_base -lha --git"
alias tree="$eza_base --tree --level=2"

alias gs="git status"
alias ga="git add ."
alias gc="git commit -m"
alias gp="git pull"
alias gP="git push"

alias weather="curl wttr.in/didymoteicho"

alias avante='nvim -c "lua vim.defer_fn(function()require(\"avante.api\").zen_mode()end, 100)"'
