#!/usr/bin/zsh

if [[ -f $HOME/.env ]]; then
  if [[ $- == *a* ]]; then
    source "$HOME/.env"
  else
    set -a
    source "$HOME/.env"
    set +a
  fi
fi

export QT_QPA_PLATFORMTHEME=qt6ct
export JQ_COLORS="0;90:38;5;180:38;5;180:37:38;5;107:37:37:38;5;117"

export TMPDIR=/tmp

export PATH="$HOME/.local/bin:$PATH"
export PATH="/usr/bin:$PATH"
export PATH="/usr/bin/go/bin:$PATH"
export PATH="$HOME/neovim/bin:$PATH"
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"

export ANDROID_HOME="$HOME/Android/Sdk"
export ANDROID_SDK_ROOT=$ANDROID_HOME
export ANDROID_AVD_HOME=$HOME/.config/.android/avd

export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator

export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_DIRS="/usr/local/share:/usr/share:/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_RUNTIME_DIR="/run/user/$UID"

export XKB_DEFAULT_LAYOUT="us,gr"
export XKB_DEFAULT_OPTIONS="grp:alt_shift_toggle"

export EDITOR="nvim"
export VISUAL="gvim"
export SUDO_EDITOR=$EDITOR
export BROWSER="brave"
export EDGE_PATH=/usr/bin/brave
export MANPAGER="nvim +Man!"
export MANWIDTH=999
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/.ripgreprc"
if [[ -n $TTY ]]; then
  export GPG_TTY=$TTY
elif [[ -t 0 ]]; then
  GPG_TTY=$(tty)
  export GPG_TTY
fi

export NODE_OPTIONS="--max-old-space-size=8192 --disable-warning=ExperimentalWarning"
export NODE_COMPILE_CACHE="$HOME/.cache/node-compile-cache"

export DESKTOP="192.168.1.2"
export LAPTOP="192.168.1.3"

[ "${HOST:-$HOSTNAME}" = "arch-desktop" ] && export ULTRAWIDE=1

export SUDO_PROMPT=$'\e[1;31mPassword:\e[0m '

export EXPO_NO_TYPESCRIPT_SETUP=1
export EAS_LOCAL_BUILD_WORKINGDIR="$HOME/.tmp"
export LSP_USE_PLISTS=true

if [[ -n $WAYLAND_DISPLAY ]]; then
  export ELECTRON_OZONE_PLATFORM_HINT=wayland
fi

if [[ $ULTRAWIDE == 1 ]]; then
  export EMULATOR_WIDTH=687
else
  export EMULATOR_WIDTH=473
fi

# zsh-system-clipboard
if [[ "$XDG_SESSION_TYPE" == "wayland" || -n "$WAYLAND_DISPLAY" ]]; then
  export ZSH_SYSTEM_CLIPBOARD_METHOD=wlc

elif [[ "$XDG_SESSION_TYPE" == "x11" || -n "$DISPLAY" ]]; then
  export ZSH_SYSTEM_CLIPBOARD_METHOD=xsc

elif [[ "$XDG_SESSION_TYPE" == "tty" && -n "$TMUX" ]]; then
  export ZSH_SYSTEM_CLIPBOARD_METHOD=tmux
fi
