#!/usr/bin/zsh

if [ -f ~/.env ]; then
  set -a
  source ~/.env
  set +a
fi

. ~/dotfiles/shell/common/fzf

export THEME="${THEME:-linux_tty}"
export GTK_THEME="Tokyonight-Dark"
export QT_QPA_PLATFORMTHEME=qt6ct
export BAT_THEME=tokyonight
export BAT_STYLE="changes,header-filename,numbers,snip"
export JQ_COLORS="0;90:33:33:37:32:37:37:36" # tokyonight

export TMPDIR=/tmp
export ZSH_COMPDUMP="${ZDOTFILES}/.zcompdump"

export PATH="$HOME/.local/bin:$PATH"
export PATH="/usr/bin:$PATH"
export PATH="/usr/bin/go/bin:$PATH"
export PATH="$HOME/asdf:$PATH"
export PATH="$HOME/.config/emacs/bin:$PATH"
export PATH="$HOME/neovim/bin:$PATH"
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

export ANDROID_HOME="$HOME/Android/Sdk"
export ANDROID_SDK_ROOT=$ANDROID_HOME
export ANDROID_AVD_HOME=$HOME/.config/.android/avd

export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_DATA_DIRS="/usr/local/share:/usr/share:/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_RUNTIME_DIR=/run/user/$(id -u)

export XKB_DEFAULT_LAYOUT="us,gr"
export XKB_DEFAULT_OPTIONS="grp:alt_shift_toggle"

export EDITOR="nvim"
export VISUAL="nvim"
export BROWSER="brave"
export EDGE_PATH=$(which brave)
export MANPAGER="nvim +Man!"
export MANWIDTH=999
export COLORTERM=truecolor

export GPG_TTY=$(tty)

export NODE_OPTIONS="--max-old-space-size=8192 --disable-warning=ExperimentalWarning"
export NODE_COMPILE_CACHE="$HOME/.cache/node-compile-cache"

export DESKTOP="192.168.1.2"
export LAPTOP="192.168.1.3"

export SUDO_PROMPT="$(tput setaf 1 bold)Password:$(tput sgr0) "

export EXPO_NO_TYPESCRIPT_SETUP=1
export NOTMUCH_PROFILE=default
export LSP_USE_PLISTS=true

if [[ -n $WAYLAND_DISPLAY ]]; then
  export ELECTRON_OZONE_PLATFORM_HINT=wayland
fi

if [ "$ULTRAWIDE" ]; then
  export EMULATOR_WIDTH=687
else
  export EMULATOR_WIDTH=473
fi

# zsh-system-clipboard
if [[ "$XDG_SESSION_TYPE" == "wayland" || -n "$WAYLAND_DISPLAY" ]]; then
  export ZSH_SYSTEM_CLIPBOARD_METHOD=wlc

elif [[ "$XDG_SESSION_TYPE" == "x11" || -n "$DISPLAY" ]]; then
  export ZSH_SYSTEM_CLIPBOARD_METHOD=xsc

elif [[ "$XDG_SESSION_TYPE" == "tty" && -n "$TMUX" ]]; then
  export ZSH_SYSTEM_CLIPBOARD_METHOD=tmux
fi
