#!/usr/bin/zsh

e() {
  local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
  yazi "$@" --cwd-file="$tmp"
  if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
    builtin cd -- "$cwd" || exit
  fi
  rm -f -- "$tmp"
}

lazygit() {
  ~/dotfiles/lazygit/launch-lazygit "$@"
}

fv() {
  local file
  file="$(
    find "${1:-.}" -path '*/\.*' -prune -o -type f -print 2>/dev/null |
      fzf +m \
        --preview='tree -C {} | head -n $FZF_PREVIEW_LINES' \
        --preview-window='right:hidden:wrap' \
        --bind=ctrl-v:toggle-preview \
        --bind=ctrl-x:toggle-sort \
        --header='(view:ctrl-v) (sort:ctrl-x)'
  )" || return
  nvim "$file" || return
}

wake-desktop() {
  wol "$DESKTOP_MAC"
}

sus-desktop() {
  ssh "$DESKTOP" 'sudo -S systemctl suspend'
}

export-lan-ip() {
  export LAN_IP=$(ip -4 -o addr show scope global | awk '{print $4}' | cut -d/ -f1 | head -n 1)
}
