#!/usr/bin/zsh

export FZF_DEFAULT_COMMAND="fd --type file --follow --hidden --exclude .git"

FZF_TOKYONIGHT="\
  --color=bg:#000000 \
  --color=bg+:#16161e  \
  --color=border:#27a1b9 \
  --color=fg:#d4d4d4 \
  --color=gutter:#16161e \
  --color=header:#434a65 \
  --color=hl+:#7dcfff \
  --color=hl:#7dcfff \
  --color=info:#545c7e \
  --color=marker:#545c7e \
  --color=pointer:#545c7e \
  --color=prompt:#a9b7e8 \
  --color=query:#a9b7e8 \
  --color=scrollbar:#27a1b9 \
  --color=separator:#292e42 \
  --color=spinner:#ff007c \
"

FZF_LINUX_TTY="\
  --color=bg:#111111 \
  --color=bg+:#000000 \
  --color=border:#555555 \
  --color=fg:#aaaaaa \
  --color=gutter:#000000 \
  --color=header:#555555 \
  --color=hl:#00aaaa \
  --color=hl+:#00aaaa \
  --color=info:#555555 \
  --color=marker:#00aa00 \
  --color=pointer:#aaaaaa \
  --color=prompt:#aaaaaa \
  --color=query:#aaaaaa \
  --color=scrollbar:#555555 \
  --color=separator:#555555 \
  --color=spinner:#aa00aa \
"

FZF_VSCODE="\
  --color=bg:#1f1f1f \
  --color=bg+:#222222 \
  --color=border:#1f1f1f \
  --color=fg:#d4d4d4 \
  --color=gutter:#2D2D2D \
  --color=header:#646695 \
  --color=hl:#C586C0 \
  --color=hl+:#608b4e \
  --color=info:#8db9e2 \
  --color=marker:#4EC9B0 \
  --color=pointer:#4EC9B0 \
  --color=prompt:#C586C0 \
  --color=query:#d4d4d4:regular \
  --color=scrollbar:#2d2d2d \
  --color=separator:#223e55 \
  --color=spinner:#4ec9b0 \
"

FZF_THEME="FZF_$(echo "$THEME" | tr '[:lower:]' '[:upper:]')"

if [ -n "$ZSH_VERSION" ]; then
  zstyle ':fzf-tab:*' use-fzf-default-opts yes

  history_file="$HOME/.fzf_history"
else
  history_file="$HOME/.bash_history"
fi

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --ignore-case
  --bind ctrl-n:down,ctrl-p:up,ctrl-d:page-down,ctrl-u:page-up,ctrl-e:accept,ctrl-k:next-history,ctrl-j:prev-history \
  --highlight-line \
  --no-bold \
  --info=inline-right \
  --ansi \
  --cycle \
  --layout=reverse \
  --border=none \
  --no-separator \
  --history=$history_file \
  $(eval echo \$"$FZF_THEME")
"

zstyle ':fzf-tab:*' fzf-flags '--color=fg:#c0caf5,bg:#16161e,fg+:#c0caf5,bg+:#343a55'
