#!/usr/bin/zsh

export FZF_DEFAULT_COMMAND="fd --type file --follow --hidden --exclude .git"

FZF_TOKYONIGHT="\
  --color=bg:#000000 \
  --color=bg+:#16161e  \
  --color=border:#27a1b9 \
  --color=fg:#d4d4d4 \
  --color=gutter:#16161e \
  --color=header:#434a65 \
  --color=hl+:#7dcfff \
  --color=hl:#7dcfff \
  --color=info:#545c7e \
  --color=marker:#545c7e \
  --color=pointer:#545c7e \
  --color=prompt:#a9b7e8 \
  --color=query:#a9b7e8 \
  --color=scrollbar:#27a1b9 \
  --color=separator:#292e42 \
  --color=spinner:#ff007c \
"

FZF_VSCODE="\
  --color=bg:#18191a \
  --color=bg+:#1f1f1f \
  --color=border:#444444 \
  --color=fg:#808080 \
  --color=gutter:#18191a \
  --color=header:#636369 \
  --color=hl:#c586c0 \
  --color=hl+:#c586c0 \
  --color=info:#636369 \
  --color=marker:#81b88b \
  --color=pointer:#569cd6 \
  --color=prompt:#d4d4d4 \
  --color=query:#d4d4d4 \
  --color=scrollbar:#424242 \
  --color=separator:#444444 \
  --color=spinner:#c586c0 \
"

FZF_THEME="FZF_$(echo "$THEME" | tr "[:lower:]" "[:upper:]")"

if [ -n "$ZSH_VERSION" ]; then
  zstyle ':fzf-tab:*' use-fzf-default-opts yes

  history_file="$HOME/.fzf_history"
else
  history_file="$HOME/.bash_history"
fi

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --ignore-case
  --bind ctrl-n:down,ctrl-p:up,ctrl-d:page-down,ctrl-u:page-up,ctrl-e:accept,ctrl-k:next-history,ctrl-j:prev-history \
  --highlight-line \
  --no-bold \
  --info=inline-right \
  --ansi \
  --cycle \
  --layout=reverse \
  --border=none \
  --no-separator \
  --history=$history_file \
  $(eval echo \$"$FZF_THEME")
"

FZF_TAB_TOKYONIGHT="--color=fg:#c0caf5,bg:#16161e,fg+:#c0caf5,bg+:#343a55"
FZF_TAB_VSCODE="--color=fg:#808080,bg:#121314,fg+:#D4D4D4,bg+:#1F1F1F"

FZF_TAB_THEME="FZF_$(echo "$THEME" | tr "[:lower:]" "[:upper:]")"
zstyle ":fzf-tab:*" fzf-flags $(eval echo \$"$FZF_TAB_THEME")
