#!/usr/bin/zsh

if [ -f ~/.env ]; then
  source ~/.env
fi

FONT=HackNerdFont-Regular:size=

if [[ "$HOST" == "arch-desktop" ]]; then
  FONT="$FONT"10
else
  FONT="$FONT"9
fi

foot --override include=~/dotfiles/foot/"${THEME:-onedark}".ini --font="$FONT"
