#!/usr/bin/zsh

if [ -f ~/.env ]; then
  source ~/.env
fi

FONT=HackNerdFontMono-Regular:size=

if [ "$ULTRAWIDE" ]; then
  FONT="$FONT"10
else
  FONT="$FONT"11
fi

foot --override include=~/dotfiles/foot/"${THEME:-tokyonight}".ini --font="$FONT"
