#!/usr/bin/zsh

if [ -f ~/.env ]; then
  source ~/.env
fi

FONT=HasklugNerdFontMono-Regular:size=

if [ "$ULTRAWIDE" ]; then
  FONT="$FONT"11
else
  FONT="$FONT"10
fi

foot --override include=~/dotfiles/foot/vscode.ini --font="$FONT" "$@"
